### ISSUE TITLE
create swap timesout when swap size is set twice the system memory 

### ISSUE THREAD

**Issue by natarjay** [sous-chefs/swap#26]
Create swap file times out for large swap size. 
The create_swapfile used shell_out which raises Chef::Exceptions::CommandTimeout when the command does not complete within time out seconds which defaults to  60s.

``` ruby
def create_swapfile(command)
  shell_out!(command)
  Chef::Log.info("#{@new_resource} Creating empty file at #{@new_resource.path}")
  Chef::Log.debug("#{@new_resource} Empty file at #{@new_resource.path} created using command '#{command}'")
end
```

Has anyone else seen this error? 
Can the timer be updated to a configurable value? 

Seen on OS: Ubuntu
chef: 12.3.0

**Comment by atward** [comment]
Hash of options can be passed to shell_out!, but cookbook would have to support it accepting a timeout
