### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rmoriz** [sous-chefs/swap#27]
Would you mind cutting a new release and upload it to the supermarket?

Thanks!

**Comment by mike-stewart** [comment]
Would be great to get a new release @sethvargo. I'm getting the following warning on Chef 12.11, which was fixed in #24.

```
WARN: Class Chef::Provider::SwapFile does not declare 'provides :swap_file'.
WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.
```

**Comment by trappar** [comment]
👍

**Comment by starx** [comment]
Wonder why @sethvargo is not releasing the updates?

**Comment by gionn** [comment]
@sethvargo ping if this cookbook needs new maintainers!

**Comment by tas50** [comment]
Seth was kind enough to transfer this cookbook over to the Sous Chefs so we can continue maintaining the cookbook and crowd source the work. Expect a Chef 13 compatible release out today.
