### ISSUE TITLE
`fallback_swap_creation_command` method in that provider should really be deleted and `dd_command` used directly

### ISSUE THREAD

**Issue by rshade** [sous-chefs/swap#46]
per lamont: `fallback_swap_creation_command` method in that provider should really be deleted and `dd_command` used directly

**Comment by damacus** [comment]
I'm not totally sure that falling back from a command that is quicker, is a great idea.

https://stackoverflow.com/questions/257844/quickly-create-a-large-file-on-a-linux-system
