### ISSUE TITLE
fc25 does not have a /etc/fstab for persist. 

### ISSUE THREAD

**Issue by rshade** [sous-chefs/swap#48]
fc25 does not have a /etc/fstab for persist.

**Comment by damacus** [comment]
Seems only to be in dokken.

**Comment by damacus** [comment]
Closing as this is everywhere in Dokken/Docker. 

We can fix by using this in the dokken.yml 
```
internediate_instructions:
      - RUN if [ ! -f /etc/fstab ];then touch /etc/fstab fi
```
