### ISSUE TITLE
Support for increasing existing swap

### ISSUE THREAD

**Issue by linuxnix** [sous-chefs/swap#55]
### Cookbook version
All versions of cookbook
### Chef-client version
12.21
### Platform Details
RHEL7.x

### Scenario:
We have a requirement to increase swap from 2Gig to 4Gig in our organization. As this cookbook is not idempotent we have to write below redundant code to increase the swap size.

swap_file '/swap' do # ~FC005
  action  :remove
  only_if { ::File.exist?('/swap')}
end

swap_file '/swap' do # ~FC005
  size 4096 # MBs
  persist true
  action  :create
end

This intern causing Foodcritic warning FC005. The code in your https://github.com/sous-chefs/swap/blob/master/resources/file.rb for existing swap is 
 if swap_enabled?
    Chef::Log.debug("#{new_resource} already created - nothing to do")

If you can implement idempotent on this that will be great.

### Steps to Reproduce:
Create a swapfile of 2Gig in a system and use below command to increase that to 4gig, the code will be skipped.

swap_file '/swap' do # ~FC005
  size 4096 # MBs
  persist true
  action  :create
end

### Expected Result:
I am expecting idempotent for this resource, irrespective of how much swap we have, the resource should be idempotent as similar to other chef resources. Can you implement something like action :modify?

### Actual Result:
NA

**Comment by damacus** [comment]
Closed via #56
